### ISSUE TITLE
[Bug]: Client error after login

### ISSUE THREAD

**Issue by pichoemr** [lenra-io/lenra_cli#162] opened 2023-01-24 10:17 UTC
### What happened?

I have two errors after the connection on backoffice, with or without keep-me-login.

### What browsers are you seeing the problem on?

Chrome (or chrome-based)

### Version

backoffice v1.0.0-beta.28

### Relevant log output

```Shell
setState() or markNeedsBuild() called during build.
This _InheritedProviderScope<AuthModel?> widget cannot be marked as needing to build because the
framework is already in the process of building widgets. A widget can be marked as needing to be
built during the build phase only if one of its ancestors is currently building. This exception is
allowed because the framework builds parent widgets before children, which means a dirty descendant
will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  _InheritedProviderScope<AuthModel?>
The widget which was currently being built when the offending call was made was:
  DefaultSelectionStyle
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/flutter/src/widgets/framework.dart 4549:11                           <fn>
packages/flutter/src/widgets/framework.dart 4563:14                           markNeedsBuild
packages/provider/src/inherited_provider.dart 577:5                           markNeedsNotifyDependents
packages/flutter/src/foundation/change_notifier.dart 351:24                   notifyListeners
packages/client_common/models/status.dart 41:22                               handle
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/client_common/models/status.dart 33:19                               handle
packages/client_common/models/auth_model.dart 70:35                           refresh

==============================================================================================

dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/go_router/src/router.dart 300:21                                     of
packages/client_common/navigator/common_navigator.dart 112:26                 go
packages/client_backoffice/navigation/guard.dart 28:21                        _toWelcome
packages/client_common/navigator/guard.dart 38:33                             guards$
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1653:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
```

**Comment by jonas-martinez** [comment] 2023-01-24 12:09
I have the same error but it does not crash the client. It should be able to show the UI properly.
This means that I cannot reproduce this issue. Can anyone else try to reproduce this issue ? (the error above should be shown and the UI must not crash) @lenra-io/devs

**Comment by taorepoara** [comment] 2023-01-24 14:10
I can't reproduce this error...

**Comment by jonas-martinez** [comment] 2023-01-27 11:20
I'm closing this issue for the moment as the error is not reproducible, don't hesitate to open it back if you think that the error is still present after making sure that your local repositories are up to date.

**Closed by jonas-martinez** 2023-01-27 11:20 UTC
Labels: bug
